### ISSUE TITLE
Bug in TOnE

### ISSUE THREAD

**Issue by karoeck** [TWUOnline/tone#4]
**Describe the bug**
Unit 2, Activity 2.3: Starting a Course Blueprint
The link for Section 12.9 takes the learner to Section 9.6

**Comment by scottmacklin** [comment]
Please re-assign to someone else.

_Scott

**Comment by kmarjanovic** [comment]
@karoeck 
Thank you for catching that Karen!  I've fixed the hyperlink.
Kelly
